const natural = require('natural');

class AIDetector {
  static analyzeCode(code, typingMetrics = {}) {
    const analysis = {
      typingPattern: this.analyzeTypingPattern(typingMetrics),
      codePatterns: this.analyzeCodePatterns(code),
      overallSuspicionScore: 0
    };

    // Calculate overall suspicion score (0-100)
    analysis.overallSuspicionScore = this.calculateSuspicionScore(analysis);

    return analysis;
  }

  static analyzeTypingPattern(metrics) {
    if (!metrics.intervals || metrics.intervals.length === 0) {
      return {
        avgInterval: 0,
        variance: 0,
        suspiciousScore: 0
      };
    }

    const intervals = metrics.intervals.filter(i => i > 0);
    const avgInterval = intervals.reduce((a, b) => a + b, 0) / intervals.length;

    // Calculate variance
    const variance = intervals.reduce((a, b) =>
      a + Math.pow(b - avgInterval, 2), 0
    ) / intervals.length;

    let suspiciousScore = 0;

    // AI-generated code often has very consistent typing patterns
    if (variance < 50) {
      suspiciousScore += 30; // Too consistent
    }

    // Or very inconsistent (pasted in chunks)
    if (variance > 5000) {
      suspiciousScore += 40; // Too inconsistent
    }

    // Extremely fast typing
    if (avgInterval < 30) {
      suspiciousScore += 25;
    }

    // Perfect rhythm (suspicious)
    const rhythmScore = this.calculateRhythmScore(intervals);
    if (rhythmScore > 0.9) {
      suspiciousScore += 20;
    }

    return {
      avgInterval: Math.round(avgInterval),
      variance: Math.round(variance),
      suspiciousScore: Math.min(100, suspiciousScore)
    };
  }

  static calculateRhythmScore(intervals) {
    if (intervals.length < 10) return 0;

    // Check if intervals are too similar
    const avgInterval = intervals.reduce((a, b) => a + b, 0) / intervals.length;
    const similarIntervals = intervals.filter(
      i => Math.abs(i - avgInterval) < 10
    ).length;

    return similarIntervals / intervals.length;
  }

  static analyzeCodePatterns(code) {
    const lines = code.split('\n');
    const totalLines = lines.length;

    // Comment detection
    const comments = code.match(/\/\/|\/\*|\*\/|#|'''|"""/g) || [];
    const commentRatio = totalLines > 0 ? comments.length / totalLines : 0;

    // AI signature patterns
    const aiPatterns = [
      /\/\/ (Generated by|Created by|Written by) (AI|ChatGPT|Claude|GPT|Assistant)/i,
      /Here (is|are) (a|the) (solution|implementation|code)/i,
      /I'll (create|write|implement|generate)/i,
      /\b(as an AI|as a language model|as an assistant)\b/i,
      /Let me (create|write|implement)/i,
      /Certainly[!,]? (Here|I)/i,
      /def (solution|solve|answer)_?\d*\(/i,
      /function (solution|solve|answer)_?\d*\(/i,
      /class Solution\d*/i, // Common in LeetCode-style AI responses
      /TODO: (Implement|Add|Write) this/i,
      /Example (usage|output):/i,
      /This (function|code|solution) (will|does)/i
    ];

    const aiPatternsDetected = aiPatterns.filter(pattern => pattern.test(code));

    // Excessive commenting (AI tends to over-comment)
    let commentScore = 0;
    if (commentRatio > 0.4) {
      commentScore = 30;
    } else if (commentRatio > 0.3) {
      commentScore = 15;
    }

    // Boilerplate detection (AI adds a lot of boilerplate)
    const boilerplatePatterns = [
      /\/\*\*[\s\S]*?\*\//g, // JSDoc comments
      /@param|@returns|@type|@description/g,
      /try\s*\{\s*[\s\S]*?\}\s*catch\s*\(/g // Excessive try-catch
    ];

    const boilerplateCount = boilerplatePatterns.reduce((count, pattern) => {
      return count + (code.match(pattern) || []).length;
    }, 0);

    const boilerplateScore = Math.min(30, boilerplateCount * 10);

    // Calculate code complexity
    const complexityScore = this.calculateComplexity(code);

    // AI-generated code often has perfect formatting
    const formattingScore = this.analyzeFormatting(code);

    // Suspicious patterns score
    const patternScore = aiPatternsDetected.length * 20;

    return {
      commentRatio: Math.round(commentRatio * 100) / 100,
      complexityScore,
      aiPatternsDetected: aiPatternsDetected.map(p => p.toString()),
      suspiciousScore: Math.min(100, commentScore + boilerplateScore + patternScore + formattingScore)
    };
  }

  static calculateComplexity(code) {
    // Simple cyclomatic complexity
    const complexityKeywords = /\b(if|else|while|for|case|catch|&&|\|\||\?)\b/g;
    const matches = code.match(complexityKeywords) || [];
    return Math.min(100, matches.length * 2);
  }

  static analyzeFormatting(code) {
    const lines = code.split('\n').filter(l => l.trim().length > 0);

    // Check for perfect indentation (suspicious)
    const indentationPattern = /^( {2}| {4}|\t)*/;
    const perfectlyIndented = lines.filter(line => {
      const match = line.match(indentationPattern);
      return match && match[0].length % 2 === 0;
    }).length;

    const perfectRatio = perfectlyIndented / lines.length;

    // AI code is often perfectly formatted
    if (perfectRatio > 0.95) {
      return 15;
    }

    return 0;
  }

  static calculateSuspicionScore(analysis) {
    const weights = {
      typing: 0.4,
      codePatterns: 0.6
    };

    const score =
      (analysis.typingPattern.suspiciousScore * weights.typing) +
      (analysis.codePatterns.suspiciousScore * weights.codePatterns);

    return Math.round(Math.min(100, score));
  }

  // Check for similarity with known AI outputs
  static checkSimilarity(code, knownAIOutputs = []) {
    if (knownAIOutputs.length === 0) return 0;

    const tokenizer = new natural.WordTokenizer();
    const tfidf = new natural.TfIdf();

    tfidf.addDocument(tokenizer.tokenize(code));
    knownAIOutputs.forEach(output => {
      tfidf.addDocument(tokenizer.tokenize(output));
    });

    // Calculate similarity scores
    let maxSimilarity = 0;
    knownAIOutputs.forEach((_, index) => {
      const similarity = this.cosineSimilarity(0, index + 1, tfidf);
      maxSimilarity = Math.max(maxSimilarity, similarity);
    });

    return maxSimilarity * 100;
  }

  static cosineSimilarity(docIndex1, docIndex2, tfidf) {
    // Simplified cosine similarity calculation
    // In production, use a proper implementation
    return 0;
  }

  // Detect rapid code completion patterns
  static detectRapidCompletion(keystrokes) {
    if (keystrokes.length < 50) return 0;

    // Check for sudden bursts of code (AI paste)
    let burstCount = 0;
    for (let i = 1; i < keystrokes.length; i++) {
      const interval = keystrokes[i].timestamp - keystrokes[i - 1].timestamp;

      // More than 20 characters in less than 100ms is suspicious
      if (interval < 100) {
        burstCount++;
      }
    }

    return Math.min(100, (burstCount / keystrokes.length) * 200);
  }
}

module.exports = AIDetector;
